### ISSUE TITLE
Small openlr's dnp(sugesstion)

### ISSUE THREAD

**Issue by guyanf** [tomtom-international/openlr-dereferencer-python#10]
Some openlr is small, the actual distance about 10 meters( and the total lines about 10 meters too ), but the smallest dnp is 29m(58.6/2).
So when I use the maximum accepted length,  the shortest path deviation is too large, then the result is error.

I adjuest some code:
(in candidates.py, about line 99)

    if current.dnp <= 30:
        point1 = [current[0], current[1]]
        point2 = [tail[0][0], tail[0][1]]
        curr_dnp = distance_pp(point1, point2)    # new function, count actual distance
    else:
        curr_dnp = current.dnp

    maxlen = (1 + MAX_DNP_DEVIATION) * curr_dnp

Other  case.
Some openlr is small, the actual distance is about 10 meters, but the total lines is about 5 meters.
So the shortest path deviation is too large, then trying other candidate.

I adjuest some code:
(in candidates.py, about line 125)

# If path does not match DNP, continue with the next candidate pair
if deviation > MAX_DNP_DEVIATION and current.dnp > 30:
            debug(
                "Shortest path deviation is too large, trying next candidate")
            continue

But the problem is still unresolved, sometimes is OK, sometimes is wrong.
I don't know what to do.

**Comment by ghost** [comment]
You are right.  This is indeed a problem when the DNP is very small.  I suggest we introduce a static buffer (configured to 30m) to the beginning and end of the range of allowed path distances.

```
minlen = ((1.0 - MAX_DNP_DEVIATION) * current.dnp) - BUFFER
maxlen = ((1.0 + MAX_DNP_DEVIATION) * current.dnp) + BUFFER
```

**Comment by guyanf** [comment]
I use the TMC data.
Some road cross like '#', they encode the cross inner links to the openlr, that have 4 small openlr in a road cross.
So when is decode the openlr, that will not match the link.

**Comment by guyanf** [comment]
@stephencurran 
That's OK!
Thank you!
