### ISSUE TITLE
about SEARCH_RADIUS

### ISSUE THREAD

**Issue by guyanf** [tomtom-international/openlr-dereferencer-python#11]
Sometimes the map coordinate is WGS84(epsg:4326).

The code in ./decoding/__init__.py (about line 23)
SEARCH_RADIUS = 100

So when I use the function 'find_lines_close_to', that will select more rows, then the program is slowly, but sometimes the radius is the distance(meters) at elsewhere.

Is it necessary to set two parameters？

Now, when I use the function 'find_lines_close_to'(my map data, epsg:4326), I set radius / 100000,  I use radius at elsewhere.

**Comment by UgnilJoZ** [comment]
Hi!

Both values are measured in meters. The `decode` function calls `find_lines_close_to` from the map implementation with that value, to find all lines within `radius` meters. I will add a comment to clarify these.

For you, this means you will have to implement a spatial query on your map. In this case it would be interesting what kind of technology you use as a backend.

**Comment by guyanf** [comment]
Hi, guy!
But seems is degree in function 'find_lines_close_to'.
I used the test-data, add print 'print(stmt)   print(lon, lat, dist)', then the result likes not meters.

    def find_lines_close_to(self, coord: Coordinates,
                            dist: float) -> Iterable[Line]:
        "Yields all lines in a given radius"
        lon, lat = coord.lon, coord.lat
        stmt = """SELECT rowid FROM lines WHERE Distance(MakePoint(?, ?), path) < ?"""

        print(stmt)
        print(lon, lat, dist)
        for (line_id, ) in self.connection.execute(stmt, (lon, lat, dist)):
            print(line_id)
            yield Line(self, line_id)


This is result, likes all line_id had been fetched.(in test data , total lines is 19.)

SELECT rowid FROM lines WHERE Distance(MakePoint(?, ?), path) < ?
13.397537469863892 52.579439878463745 100.0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
SELECT rowid FROM lines WHERE Distance(MakePoint(?, ?), path) < ?
13.389647469863892 52.57432987846374 100.0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
[Line with id=11 of length 203.59199885442638, Line with id=12 of length 360.3709571921746]


I don't known the reason!
Thanks.

**Comment by guyanf** [comment]
Hi!  @UgnilJoZ 
Is there any mistake when I use it? 
Thanks!

**Comment by UgnilJoZ** [comment]
Didn't mean to close this, sorry.

We found indeed that Spatialite's Distance function has to be called in a certain way to return a result in meters.

Thus, the current implementation returns too many lines, causing the result computation to be longer than needed. I'll file a PR to catch that.

**Comment by guyanf** [comment]
Hi.
It doesn't matter.
The map distance is usual map unit, then the distance is degree when epsg is 4326.

Must be reproject the coord or change the distance unit.

I use the postgis. function st_dwithin.

**Comment by guyanf** [comment]
But when I use the spatialite, have the same question.

**Comment by guyanf** [comment]
That's OK!
I have change my code(use postgis).

ST_DWithin(geography gg1, geography gg2, double precision distance_meters, boolean use_spheroid);
