### ISSUE TITLE
about 'LRDecodeError'

### ISSUE THREAD

**Issue by guyanf** [tomtom-international/openlr-dereferencer-python#15]
Hi!
At the 'candidates.py', when the openlr didn't decode location references, the program will exit.
But sometimes should have some infomation.

I add some code at the end of the 'candidates.py'.
  try:
        raise LRDecodeError()
    except LRDecodeError:
        print('no candidates links.')

or change class LRDecodeError.

**Comment by UgnilJoZ** [comment]
Hi,

I added some hint that the candidates are consumed, if they are.
