### ISSUE TITLE
About p_off and n_off

### ISSUE THREAD

**Issue by guyanf** [tomtom-international/openlr-dereferencer-python#16]
Hi! guy!
May be the p_off and n_off is offset of the total path, not the dnp.
Because they are always different.

In the 'tools.py'

def build_line_location(lines: List[Line],
                        reference: LineLocationRef) -> LineLocation:
    """Builds a LineLocation object from the location reference path and the offset values.

    The result will be a trimmed list of Line objects, with minimized offset values"""
    p_off = reference.poffs * reference.points[0].dnp
    print(reference.noffs)
    print(reference.points[-2].dnp)
    n_off = reference.noffs * reference.points[-2].dnp
    print(n_off)
    adjusted_lines, p_off, n_off = remove_unnecessary_lines(
        lines, p_off, n_off)
    print(n_off)
    return LineLocation(adjusted_lines, p_off, n_off)

**Comment by ghost** [comment]
I think this could indeed cause problems.  We should compute the positive and negative offsets as a function of the length of the path found between 2 location reference points, not as a function of the DNP.

**Comment by UgnilJoZ** [comment]
This [is now fixed](https://github.com/tomtom-international/openlr-dereferencer-python/blob/master/openlr_dereferencer/decoding/line_location.py#L55-L56) as a side effect of #21, as the route components are now visible to `build_line_location`.
