### ISSUE TITLE
via point

### ISSUE THREAD

**Issue by guyanf** [tomtom-international/openlr-dereferencer-python#40]
Hi, guys!

Is the via point useful? Because it is not the best path that shortest path between first node and last node.
The openlr has more than 2 points(include via point). 

Thanks.

**Comment by UgnilJoZ** [comment]
Hi @guyanf !
The decoder finds the shortest path between two consecutive LRPs. 
If the line location is not a shortest path, the encoder has to insert an extra LRP.
It then references a series of shortest paths.

The full details of when an extra point is inserted can be found on page 85 of the [openLR whitepaper](https://www.openlr-association.com/fileadmin/user_upload/openlr-whitepaper_v1.5.pdf) in steps 3, 4 and 5.

**Comment by guyanf** [comment]
Thanks!
That's OK.
If the encoder include the via points, the openlr-dereferencer code can use it.
