### ISSUE TITLE
Maybe score_bear have some error

### ISSUE THREAD

**Issue by guyanf** [tomtom-international/openlr-dereferencer-python#7]
The code in scoring.py.

def score_bearing(wanted: LocationReferencePoint, candidate: Line, is_last_lrp: bool) -> float:
    """Scores the difference between expected and actual bearing angle.

    A difference of 0° will result in a 1.0 score, while 180° will cause a score of 0.0."""
    point1 = candidate.start_node.coordinates
    point2 = get_bearing_point(candidate)
    bear = degrees(bearing(point1, point2))
    expected_bearing = BEAR_MULTIPLIER * wanted.bear
    if is_last_lrp:
        return score_angle_difference(expected_bearing, bear - 180)
    return score_angle_difference(expected_bearing, bear)

If the line is last lrp, the point1's coordinates is start_node,maybe is error, the right is end_node.

another quertion.
why use the 'BEAR_MULTIPLIER'

**Comment by guyanf** [comment]
This is new code:
and set BEAR_MULTIPLIER = 1, I don't known the reason, but like's that is right.


def score_bearing(wanted: LocationReferencePoint, candidate: Line,
                  is_last_lrp: bool) -> float:
    """Scores the difference between expected and actual bearing angle.

    A difference of 0° will result in a 1.0 score, while 180° will cause a score of 0.0."""
    point1 = candidate.start_node.coordinates
    if is_last_lrp:
        point1 = candidate.end_node.coordinates
        point2 = get_bearing_point(candidate, True)
    else:
        point1 = candidate.start_node.coordinates
        point2 = get_bearing_point(candidate)

    bear = degrees(bearing(point1, point2))

    # debug('point({} {}) point({} {}) {}'.format(point1.lon, point1.lat,
    #                                             point2.lon, point2.lat, bear))
    expected_bearing = BEAR_MULTIPLIER * wanted.bear
    # print(is_last_lrp)
    # if not is_last_lrp:
    #     return score_angle_difference(expected_bearing, bear - 180)

    # print(score_angle_difference(expected_bearing, bear), is_last_lrp)
    return score_angle_difference(expected_bearing, bear)

**Comment by UgnilJoZ** [comment]
Hi - thank you for your input!

Indeed, we found some errors in the bearing calculation. I intend to fix them in #9 .

**Comment by UgnilJoZ** [comment]
The issues were:
- As the `openlr` module returns the bearing angle in degrees meanwhile, the inital reason for a `BEAR_MULTIPLIER` was solved away.
- An error in calculating the bearing angle backwards.

Both seem now fixed to me. Same for you?

**Comment by guyanf** [comment]
That's OK!
Thanks!
